version: '2'
services:
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './hosts:/etc/nginx/conf.d'
      - './www:/var/www'
      - './logs:/var/log/nginx'
    links:
      - php
  php:
    build: ./images/php
    links:
      - mysql
      - redis
    volumes:
      - './www:/var/www'
    environment:
      XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST} remote_port=${XDEBUG_REMOTE_PORT} remote_connect_back=${XDEBUG_REMOTE_CONNECT_BACK}
  redis:
    image: 'redis:5.0.5'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  mysql:
    image: 'mariadb:10.3'
    ports:
      - '3306:3306'
    volumes:
      - './mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql
